development:
  adapter:  mysql
  database: <%= @database_development %>
  encoding: utf8
  username: root
  password: 
  host:     localhost

test:
  adapter:  mysql
  database: <%= @database_test %>
  encoding: utf8
  username: root
  password:
  host:     localhost

production:
  adapter:  mysql
  database: <%= @database_production %>
  encoding: utf8
  username: rails
  password: ***REMOVED***
  host:     server.manualdesign.no
