require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "spec/internal/db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"
    - "lib/rails/generators/**/*_generator.rb"

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "**/*_spec.rb"
    - "**/*.builder"
    - "db/migrate/**/*"
    - "config/routes.rb"
    - "spec/factories/**/*.rb"
    - "spec/rails_helper.rb"

Metrics/ClassLength:
  Exclude:
    - "db/migrate/*"

Metrics/MethodLength:
  Exclude:
    - "app/models/concerns/pages_core/page_model/dated_page.rb"
    - "db/migrate/*"
    - "lib/rails/generators/**/*_generator.rb"

Metrics/ParameterLists:
  Exclude:
    - "app/helpers/pages_core/labelled_form_builder.rb"

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - "config/routes.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  AutoCorrect: true
  Max: 80

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

Lint/MissingSuper:
  Exclude:
    - "lib/pages_core/templates/configuration_handler.rb"
    - "lib/pages_core/templates/configuration_proxy.rb"

Rails:
  Enabled: true

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_email

Rails/ApplicationController:
  Exclude:
    - "app/controllers/pages_core/base_controller.rb"

Rails/CreateTableWithTimestamps:
  Exclude:
    - "db/migrate/20111219033112_create_pages_tables.rb"

Rails/HelperInstanceVariable:
  Exclude:
    - "app/helpers/pages_core/admin/form_builder.rb"
