# inherit_from:
#   - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/internal/db/schema.rb'
  TargetRubyVersion: 2.1

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
  ExcludedMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw

Metrics/ClassLength:
  Exclude:
    - "db/migrate/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false
