require: rubocop-rspec

#inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/internal/db/schema.rb'

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "spec/internal/config/environments/*"
    - "config/routes.rb"
    - "db/migrate/*"
    - "**/*_spec.rb"
    - "spec/factories.rb"
    - "spec/rails_helper.rb"

Metrics/ClassLength:
  Exclude:
    - "db/migrate/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false
