inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/internal/db/schema.rb'
  TargetRubyVersion: 2.1

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Metrics/ClassLength:
  Exclude:
    - "db/migrate/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Rails:
  Enabled: true

StringLiterals:
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false
