language: ruby
sudo: false
cache: bundler
services:
  - postgresql
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.1
env:
  - CI=1
script:
- bundle exec rspec spec
before_script:
- psql -c 'create database pages_test' -U postgres
- bundle exec rake db:migrate
