addons:
  code_climate:
    repo_token: d87d77f1b738c1004ddad858c46206711433daa5c47f644d7495e9afe0012cb0
language: ruby
sudo: false
cache: bundler
notifications:
  slack:
    secure: iWxT+IWkZSy1XvDhCKbj9BF/Wcm2Ygcoypf9iAPxSSBiP7L8hMdXCsJSU7Bq1t8o/fHwfkhbe8awJ9F+z+MDSST6JYH2aKTn0okSqvHpN25RK4WStrpiyDnMweCYZRJsrZJoHlfy8lOhY+k/aAav6neBiIrU1zQ3iiTPlK0Tnb3LU4wUoXo1NDuGr/Vo4oVIveSC96Tzg+lM36KRGOlns2mdBhgXl6nlRa3sBHYB70AcZEaijJ4uzd7gjCI9hxmO0YWX9goJOGv094PsNxgfqUaSKBzHPuaWHVxFd5XbAYi2CQEkOjqErwcn99zBSqKHAwE2g02FmeyjNMQevVBSuRFhGELtDHkTn/ttRalhZFn48rdXiWTS53/rYWDu+j+syN09iQqoikPK7JIfuADXqlhq6L8a1UPFPLKvpuK/Qx7aM8kNnsUabHIEpj828akzQSbAI6dkcY05eXEtT0brrO3WkzoRSJUjb0e6vYXilR+BXN15g6UFPs5MZWfkW4I6AI3efD789kN7myJM2jchVlL2U5erkOAr6s3FPE4xEN4J2ne0j7rpIFdpbtk7l7BXwbC6WCsfRlb1z5+jtIPVB6IfWOvl2dmyilr43o0AbYfg+hd51Bx47l5KsdP4nrBsUT4ePwVZPm11n0dqd9Hj71x8riTIXlqYq78JQwfQFdY=
services:
- mysql
rvm:
- 2.2.3
env:
- DB=mysql
- DB=postgres
script:
- bundle exec rspec spec
before_script:
- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database pages_test;'; fi"
- sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database pages_test' -U postgres; fi"
- bundle exec rake db:migrate
