language: ruby
sudo: false
cache: bundler
services:
  - mysql
rvm:
  - 2.2.3
env:
  - DB=mysql
  #- DB=postgres
script:
  - bundle exec rspec spec
before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database pages_test;'; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'create database pages_test' -U postgres; fi"
  - bundle exec rake db:migrate
